#!/usr/bin/env python3
"""
Documentation script: Shows how comparison pairs are generated.

Note: State comparison pairs are now generated dynamically in lib/db.ts
using getTopComparisonPairs() which queries the states table directly.
This generates all 50*49/2 = 1,225 state pairs automatically.

Utility comparison pairs are generated by getUtilityComparisonPairs()
which uses the top 25 utilities by customer count = 25*24/2 = 300 pairs.

No separate DB table is needed for comparisons.
"""

import sqlite3
import os
import itertools

DB_PATH = os.path.join(os.path.dirname(__file__), '..', 'data', 'power.db')


def show_stats():
    conn = sqlite3.connect(DB_PATH)
    c = conn.cursor()

    c.execute("SELECT slug FROM states ORDER BY state")
    state_slugs = [row[0] for row in c.fetchall()]

    pairs = list(itertools.combinations(state_slugs, 2))
    print(f"Total state comparison pairs: {len(pairs)}")
    print(f"Sample pairs:")
    for s1, s2 in pairs[:10]:
        print(f"  {s1}-vs-{s2}-electricity")

    c.execute("SELECT slug FROM utilities ORDER BY customers DESC LIMIT 25")
    util_slugs = [row[0] for row in c.fetchall()]
    util_pairs = list(itertools.combinations(util_slugs, 2))
    print(f"\nTop-25 utility comparison pairs: {len(util_pairs)}")
    print(f"Sample pairs:")
    for u1, u2 in util_pairs[:5]:
        print(f"  {u1}-vs-{u2}")

    conn.close()


if __name__ == '__main__':
    show_stats()
